version: 0.2

env:
  variables:
    # SOURCE_VERSION: $(echo $CODEBUILD_RESOLVED_SOURCE_VERSION)
    REPO_NAME: "https://github.com/tkazusa/ML-CICD-pipeline"

phases:
  install:
    runtime-versions:
      docker: 18
      python: 3.7
    commands:
      - pip install -r requirements.txt

  build:
    commands:
      - . ./test.sh