version: 0.2

env:
  variables:
    # SOURCE_VERSION: $(echo $CODEBUILD_RESOLVED_SOURCE_VERSION)
    REPO_NAME: "https://github.com/tkazusa/ML-CICD-pipeline"
    SRC: pipeline.py

phases:
  install:
    runtime-versions:
      docker: 18
      python: 3.7
    commands:
      - pip install -r requirements.txt

  build:
    commands:
      # Docker イメージを build して ECR へ登録
      # - . ./containers/ecr-regist-batch.sh
      # - . ./containers/ecr-regist-train.sh
      - . ./setenv.sh
      - python $SRC