preprocess:
    data_path: 's3://sfn-sagemaker-workflow/train'
    preprocessed_output_path: 's3://sfn-sagemaker-workflow'

train:
  image_url: '815969174475.dkr.ecr.us-east-1.amazonaws.com/tf-sm-process-train-gpu:latest'
  hyper_parameter: 
    batch_size: 64
    epoch: 1

